Add OIDC middleware
halilbahar/beeyond pull request #140
Opened 2021-11-24 23:34 UTC by polleichtnermoritz

endlich LETS GET THIS **** MERGED

2021-11-24 23:40 UTC, eminasljivic approved these changes

2021-11-24 23:41 UTC, halilbahar requested changes

2021-11-24 23:41 UTC, halilbahar commented on kubernetes-validation-beeyond/routers/constraint.go
> +	claims := c.Keys["props"].(jwt.MapClaims)
Use for this a middleware instead of copy pasting it into every route

2021-11-24 23:41 UTC, halilbahar commented on kubernetes-validation-beeyond/middleware/oidc.go
> +			keytxt := `-----BEGIN PUBLIC KEY-----
at first sight this looks really bad. Hardcoding a public key.
This is a really bad solution :(
All you do is decode the jwt? You can also do that on jwt.io
Anyone who generates a valid jwt token will pass this authentication check.

2022-02-01 11:15 UTC, eminasljivic commented on kubernetes-validation-beeyond/conf/config.yml
> +
Remove empty lines

2022-02-01 22:24 UTC, halilbahar approved these changes

2022-02-01 22:26 UTC, merged